version: '2.4'

services:
  pgAdmin4:
    restart: always
    container_name: pgAdmin4
    hostname: pgAdmin4
    image: dpage/pgadmin4
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL:    ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    healthcheck:
        test: wget --no-verbose --tries=1 --spider localhost:80 || exit 1
        interval: 10s
        retries: 2
        start_period: 60s
        timeout: 10s
