version: '2.4'

services:
  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - 3000:3000
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - 4242:4242
