version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - node/test:
          version: '18.10'
          pkg-manager: npm

